version: '2'
services:
    pgsqltest-elasticsearch:
        container_name: pgsqltest-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/pgsqltest/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
